<a href="https://colab.research.google.com/github/Iyobosahenry/Hamoye_Quiz/blob/main/Learning_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()

In [7]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [13]:
X = iris.data
y = iris.target

In [14]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [25]:
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [26]:
model.score(X_test, y_test)

0.9777777777777777

In [44]:
model.predict([iris.data[5]])

array([0])

In [35]:
import seaborn as sns

In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
y_pred = model.predict(X_test)

In [41]:
confusion_matrix(y_test, y_pred)

array([[18,  0,  0],
       [ 0, 13,  1],
       [ 0,  0, 13]])

array([1, 1, 0, 0, 0, 2, 2, 1, 0, 2, 0, 2, 1, 2, 0, 1, 2, 2, 0, 0, 0, 0,
       1, 0, 1, 2, 0, 0, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 0,
       0])